steps:
  - label: ":rocket: Launch test jobs"
    command: |
      export ARCH JULIA_VERSION
      for ARCH in x86_64 aarch64; do
        for JULIA_VERSION in 1 1.10 1.9; do
          buildkite-agent pipeline upload .buildkite/run_bb_tests.yml
        done
      done
    agents:
      queue: juliaecosystem
