steps:
  - label: ":rocket: Generate and launch test pipeline"
    plugins:
      JuliaCI/julia#v1:
        version: "1"
    command: |
      # Generate the pipeline dynamically
      # Options:
      #   --group-by-julia      - Group steps by Julia version
      #   --group-by-arch       - Group steps by architecture
      #   --group-by-subproject - Group steps by subproject name
      #   (no flag)             - No grouping (flat list)
      
      cd .buildkite
      julia --project -e 'import Pkg; Pkg.instantiate()'
      julia --project generate_pipeline.jl --group-by-arch | buildkite-agent pipeline upload
    agents:
      queue: juliaecosystem
      os: linux
      arch: aarch64
