steps:
  - label: ":julia: :linux: ${ARCH?} Julia ${JULIA_VERSION?}"
    plugins:
      - JuliaCI/julia#v1:
          version: "${JULIA_VERSION?}"
          arch: "${ARCH?}"
      - JuliaCI/jack#v1:
          install:
            - "GNUMake_jll"
    commands: |
      make --output-sync=target -j$$(nproc) testall
    agents:
      queue: "juliaecosystem"
      os: "linux"
      sandbox_capable: "true"
      arch: "${ARCH?}"
