steps:
  - label: ":julia: :linux: ${ARCH?} Julia ${JULIA_VERSION?} - ${SUBPROJECT_NAME?}"
    plugins:
      - staticfloat/metahook:
          post-checkout: |
            git config --global user.email "buildkite@julialang.org"
            git config --global user.name "Buildkite"
      - JuliaCI/julia#v1:
          version: "${JULIA_VERSION?}"
          arch: "${ARCH?}"
      - JuliaCI/julia-test#v1:
          project: "${SUBPROJECT?}"
    agents:
      queue: "juliaecosystem"
      os: "linux"
      sandbox_capable: "true"
      arch: "${ARCH?}"
    soft_fail: "${SOFT_FAIL}"
    timeout_in_minutes: 120
    artifact_paths:
      - "BinaryBuilderToolchains.jl/test/*-files.tar.gz"
