steps:
  - label: ":julia: :linux: ${ARCH?} Julia ${JULIA_VERSION?}"
    plugins:
      - staticfloat/metahook:
          post-checkout: |
            git config --global user.email "buildkite@julialang.org"
            git config --global user.name "Buildkite"
      - JuliaCI/julia#v1:
          version: "${JULIA_VERSION?}"
          arch: "${ARCH?}"
      - JuliaCI/jack#v1:
          install:
            - "GNUMake_jll"
    commands: |
      make --output-sync=target -j$$(nproc) testall
    agents:
      queue: "juliaecosystem"
      os: "linux"
      sandbox_capable: "true"
      arch: "${ARCH?}"
    soft_fail: "${SOFT_FAIL}"
    timeout_in_minutes: 120
