#!/bin/bash

# Copy all `HOST*` environment variables to `*`, e.g. `HOSTCC` -> `CC`, `HOSTLD` -> `LD`, etc...
function hostcc_env() {
    HOST_ENVS=( $(env | grep '^HOST' | cut -d'=' -f1) )
    for HOST_ENV in "${HOST_ENVS[@]}"; do
        ENV="${HOST_ENV#HOST}"
        export "${ENV}=${!HOST_ENV}"
    done

    # Then run the command line passed in to us.
    "$@"
}
